services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    platform: linux/arm64/v8
    container_name: logistic-postgres
    environment:
      POSTGRES_DB: logistic_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logistic-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Message Broker
  redis:
    image: redis:7-alpine
    platform: linux/arm64/v8
    container_name: logistic-redis
    command: redis-server --appendonly yes --requirepass redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - logistic-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: logistic-control-api
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://postgres:password@postgres:5432/logistic_control?sslmode=disable
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: logistic_control
      DB_SYNC: true
      DB_LOGGING: false
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - logistic-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/shipments/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Admin Interface (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/arm64/v8
    container_name: logistic-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@logistic.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - logistic-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  # Redis Commander (ARM64 desteği olmadığı için şu an devre dışı)
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   platform: linux/arm64/v8
  #   container_name: logistic-redis-commander
  #   environment:
  #     REDIS_HOSTS: local:redis:6379:0:redis_password
  #     HTTP_USER: admin
  #     HTTP_PASSWORD: admin123
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis
  #   networks:
  #     - logistic-network

  # Named Volumes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

# Networks
networks:
  logistic-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
